[package]
name = "bevy_snippets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
strum = "0.21.0"
strum_macros = "0.21.1"